# Generated by Django 6.0.1 on 2026-02-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=150)),
                ('entreprise', models.CharField(max_length=150)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('description_taches', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Expérience',
                'verbose_name_plural': 'Expériences',
            },
        ),
        migrations.CreateModel(
            name='ReseauSociaux',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('icon_reseau', models.CharField(help_text='Class font awesome Reseau', max_length=100)),
                ('lien', models.URLField()),
            ],
            options={
                'verbose_name': 'reseau social',
                'verbose_name_plural': 'reseau sociaux',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_class', models.CharField(blank=True, help_text='Class Font Awesome', max_length=50)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ProjetModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('titre', models.CharField(max_length=100)),
                ('lien_gitHub', models.URLField(blank=True, max_length=300)),
                ('image_Projet', models.ImageField(blank=True, null=True, upload_to='api/images/')),
                ('rappor_PDF', models.FileField(blank=True, null=True, upload_to='api/rapports/')),
                ('les_tags', models.ManyToManyField(related_name='projets', to='api.tags')),
            ],
            options={
                'verbose_name': 'Projet',
                'verbose_name_plural': 'Projets',
            },
        ),
    ]
