# Generated by Django 6.0.1 on 2026-02-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projetmodel',
            name='image_Projet',
            field=models.ImageField(blank=True, null=True, upload_to='api/images_projets/'),
        ),
    ]
